import type {
  DashboardSummary,
  Transaction,
} from "@/lib/types"

// ─── Dashboard ────────────────────────────────────────────────────────────────

export const MOCK_DASHBOARD: DashboardSummary = {
  wallet: {
    id: "wallet_01",
    accountNumber: "8031234567",
    balance: 245000,
    currency: "NGN",
    hasTransactionPin: true,
  },
  activeGroupsCount: 3,
  completedGroupsCount: 4,
  exitedGroupsCount: 1,
  nextContribution: {
    groupId: "group_01",
    groupName: "Lagos Hustlers Circle",
    amount: 10000,
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(), // 2 days
    daysUntilDue: 2,
  },
  nextPayout: {
    groupId: "group_02",
    groupName: "Campus Roommates Fund",
    amount: 25000,
    round: 2,
  },
  recentTransactions: [
    {
      id: "txn_01",
      type: "payout",
      amount: 60000,
      currency: "NGN",
      status: "successful",
      description: "Ajo payout — Round 1",
      reference: "AJO-PAY-001",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      groupId: "group_01",
      groupName: "Lagos Hustlers Circle",
    },
    {
      id: "txn_02",
      type: "contribution",
      amount: 10000,
      currency: "NGN",
      status: "successful",
      description: "Contribution — Round 2",
      reference: "AJO-CON-002",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
      groupId: "group_01",
      groupName: "Lagos Hustlers Circle",
    },
    {
      id: "txn_03",
      type: "deposit",
      amount: 50000,
      currency: "NGN",
      status: "successful",
      description: "Wallet top-up via card",
      reference: "DEP-003",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    },
    {
      id: "txn_04",
      type: "transfer_out",
      amount: 15000,
      currency: "NGN",
      status: "successful",
      description: "Transfer to Femi Lawal",
      reference: "TRF-004",
      counterpartyName: "Femi Lawal",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 75).toISOString(),
    },
    {
      id: "txn_05",
      type: "contribution",
      amount: 5000,
      currency: "NGN",
      status: "successful",
      description: "Contribution — Round 1",
      reference: "AJO-CON-005",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 100).toISOString(),
      groupId: "group_02",
      groupName: "Campus Roommates Fund",
    },
  ],
}
