import type {
  DashboardSummary,
  AjoGroup,
  Transaction,
} from "@/lib/types"

// ─── Dashboard ────────────────────────────────────────────────────────────────

export const MOCK_DASHBOARD: DashboardSummary = {
  wallet: {
    id: "wallet_01",
    accountNumber: "8031234567",
    balance: 245000,
    currency: "NGN",
  },
  activeGroupsCount: 3,
  completedGroupsCount: 4,
  exitedGroupsCount: 1,
  nextContribution: {
    groupId: "group_01",
    groupName: "Lagos Hustlers Circle",
    amount: 10000,
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(), // 2 days
    daysUntilDue: 2,
  },
  nextPayout: {
    groupId: "group_02",
    groupName: "Campus Roommates Fund",
    amount: 25000,
    round: 2,
  },
  recentTransactions: [
    {
      id: "txn_01",
      type: "payout",
      amount: 60000,
      currency: "NGN",
      status: "successful",
      description: "Ajo payout — Round 1",
      reference: "AJO-PAY-001",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      groupId: "group_01",
      groupName: "Lagos Hustlers Circle",
    },
    {
      id: "txn_02",
      type: "contribution",
      amount: 10000,
      currency: "NGN",
      status: "successful",
      description: "Contribution — Round 2",
      reference: "AJO-CON-002",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
      groupId: "group_01",
      groupName: "Lagos Hustlers Circle",
    },
    {
      id: "txn_03",
      type: "deposit",
      amount: 50000,
      currency: "NGN",
      status: "successful",
      description: "Wallet top-up via card",
      reference: "DEP-003",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    },
    {
      id: "txn_04",
      type: "transfer_out",
      amount: 15000,
      currency: "NGN",
      status: "successful",
      description: "Transfer to Femi Lawal",
      reference: "TRF-004",
      counterpartyName: "Femi Lawal",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 75).toISOString(),
    },
    {
      id: "txn_05",
      type: "contribution",
      amount: 5000,
      currency: "NGN",
      status: "successful",
      description: "Contribution — Round 1",
      reference: "AJO-CON-005",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 100).toISOString(),
      groupId: "group_02",
      groupName: "Campus Roommates Fund",
    },
  ],
}

// ─── Groups ───────────────────────────────────────────────────────────────────

export const MOCK_GROUPS: AjoGroup[] = [
  {
    id: "group_01",
    name: "Lagos Hustlers Circle",
    contributionAmount: 60000,
    memberShare: 10000,
    cycleLength: 6,
    frequency: "weekly",
    visibility: "private",
    status: "active",
    currentRound: 2,
    totalRounds: 6,
    creatorId: "user_01",
    myStatus: "active",
    myContributionStatus: "pending",
    myPayoutRound: 4,
    myPayoutReceived: false,
    nextContributionDate: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    members: [
      { id: "m1", userId: "user_01", fullName: "Bashir Adamu",  payoutOrder: 1, payoutRound: 1, status: "active", hasReceivedPayout: true,  contributionRate: 100 },
      { id: "m2", userId: "user_02", fullName: "Ada Obi",       payoutOrder: 2, payoutRound: 2, status: "active", hasReceivedPayout: false, contributionRate: 100 },
      { id: "m3", userId: "user_03", fullName: "Femi Lawal",    payoutOrder: 3, payoutRound: 3, status: "late",   hasReceivedPayout: false, contributionRate: 75  },
      { id: "m4", userId: "user_04", fullName: "Chioma Eze",    payoutOrder: 4, payoutRound: 4, status: "active", hasReceivedPayout: false, contributionRate: 100 },
      { id: "m5", userId: "user_05", fullName: "Tunde Bakare",  payoutOrder: 5, payoutRound: 5, status: "active", hasReceivedPayout: false, contributionRate: 100 },
      { id: "m6", userId: "user_06", fullName: "Zainab Bello",  payoutOrder: 6, payoutRound: 6, status: "active", hasReceivedPayout: false, contributionRate: 100 },
    ],
    rounds: [],
    inviteCode: "LAGOS-HUS-01",
  },
  {
    id: "group_02",
    name: "Campus Roommates Fund",
    contributionAmount: 25000,
    memberShare: 5000,
    cycleLength: 5,
    frequency: "monthly",
    visibility: "private",
    status: "active",
    currentRound: 1,
    totalRounds: 5,
    creatorId: "user_02",
    myStatus: "active",
    myContributionStatus: "paid",
    myPayoutRound: 2,
    myPayoutReceived: false,
    nextContributionDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 18).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    members: [
      { id: "m7", userId: "user_07", fullName: "Kelechi Nwosu", payoutOrder: 1, payoutRound: 1, status: "active", hasReceivedPayout: false, contributionRate: 100 },
      { id: "m8", userId: "user_01", fullName: "Bashir Adamu",  payoutOrder: 2, payoutRound: 2, status: "active", hasReceivedPayout: false, contributionRate: 100 },
      { id: "m9", userId: "user_08", fullName: "Yusuf Aliyu",   payoutOrder: 3, payoutRound: 3, status: "active", hasReceivedPayout: false, contributionRate: 100 },
    ],
    rounds: [],
    inviteCode: "CAMPUS-RM-02",
  },
  {
    id: "group_03",
    name: "Market Women Cooperative",
    contributionAmount: 100000,
    memberShare: 20000,
    cycleLength: 5,
    frequency: "weekly",
    visibility: "public",
    status: "active",
    currentRound: 3,
    totalRounds: 5,
    creatorId: "user_09",
    myStatus: "active",
    myContributionStatus: "paid",
    myPayoutRound: 5,
    myPayoutReceived: false,
    nextContributionDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 21).toISOString(),
    members: [
      { id: "m10", userId: "user_09", fullName: "Ngozi Okonkwo", payoutOrder: 1, payoutRound: 1, status: "active", hasReceivedPayout: true,  contributionRate: 100 },
      { id: "m11", userId: "user_10", fullName: "Amaka Chukwu",  payoutOrder: 2, payoutRound: 2, status: "active", hasReceivedPayout: true,  contributionRate: 100 },
      { id: "m12", userId: "user_01", fullName: "Bashir Adamu",  payoutOrder: 3, payoutRound: 3, status: "active", hasReceivedPayout: false, contributionRate: 100 },
      { id: "m13", userId: "user_11", fullName: "Bola Tinubu",   payoutOrder: 4, payoutRound: 4, status: "active", hasReceivedPayout: false, contributionRate: 100 },
      { id: "m14", userId: "user_12", fullName: "Seun Kuti",     payoutOrder: 5, payoutRound: 5, status: "active", hasReceivedPayout: false, contributionRate: 100 },
    ],
    rounds: [],
  },
]